std_msgs/Header header 
#  [] [0|0]
bool app_status__speed_limit4kmh 
#  [] [0|0]
bool app_status__send_c_a_n_dbg_messages 
#  [] [0|0]
bool app_status__pwr_assisted_braking 
#  [] [0|0]
bool signal12_switch 
#  [] [0|0]
bool request_zero_throttle 
#  [] [0|0]
bool request_brake 
#  [] [0|0]
bool signal_brights_on 
#  [] [0|0]
bool signal_right_turn 
#  [] [0|0]
bool signal_left_turn 
#  [] [0|0]
bool signal_horn 
#  [] [0|0]
bool signal_hazard_lights 
#  [] [0|0]
bool signal_fog_lights 
#  [] [0|0]
bool signal_direction_reverse 
#  [] [0|0]
bool global_man_sig_mag_brake 
#  [] [0|0]
bool global_curtis_sig_mag_brake 
#  [] [0|0]
bool signal_brake_switch 
#  [] [0|0]
bool signal_seat_switch 
#  [] [0|0]
bool e_stop_status 
#  [] [0|0]
int32 selected_application 
#  [] [0|0]
int32 selected_op_mode 
#  [] [0|0]
int32 active_op_mode 
#  [] [0|0]
bool button_blue 
#  [] [0|0]
bool button_yellow 
#  [] [0|0]
bool button_green 
