std_msgs/Header header 
#  [] [0|0]
int32 remote_status_light_blink_rate_req 
#  [] [0|0]
int32 remote_status_light_color_req 
#  [] [0|0]
bool remote_horn_req 
#  [] [0|0]
bool remote_light_brake_req 
#  [] [0|0]
bool remote_blink_left_req 
#  [] [0|0]
bool remote_blink_right_req 
#  [] [0|0]
bool remote_brights_on_req 
#  [] [0|0]
bool remote_light_reverse_req 
#  [] [0|0]
bool remote_lights_turn_left_req 
#  [] [0|0]
bool remote_lights_turn_right_req 
