dbc_file: ninaCAN6_gatewayPC_nova_v1.9.dbc
protocol_conf: zhaw_nina.yml
car_type: nina 
package_prefix: zhaw
sender_list: [RemoteDriveRequest, RemoteIndicatorRequest]
sender: GatewayPC
black_list: []

output_dir: output
config_dir: config/

